name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Accordion
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us reproduce and fix the issue.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have read the documentation
          required: true
        - label: I am using the latest version of Accordion
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create an AccordionPlan with...
        2. Add action...
        3. Execute plan...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Sample
      description: Minimal code sample that reproduces the issue
      render: java
      placeholder: |
        AccordionPlan plan = AccordionPlan.create()
            .addAction("test", ...)
            .build();
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Relevant error logs or stack traces
      render: text
      placeholder: Paste error logs here...
    validations:
      required: false

  - type: dropdown
    id: java_version
    attributes:
      label: Java Version
      description: Which Java version are you using?
      options:
        - Java 17
        - Java 18
        - Java 19
        - Java 20
        - Java 21
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: accordion_version
    attributes:
      label: Accordion Version
      description: Which version of Accordion are you using?
      placeholder: e.g., 1.0.0, main branch, commit hash
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (CentOS/RHEL)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context, screenshots, or relevant information...
    validations:
      required: false
