name: 🔧 CI/CD Failure
description: Automated issue for CI/CD pipeline failures
title: "[CI-FAILURE] "
labels: ["ci-failure", "automated-issue", "needs-investigation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        This issue was automatically created due to a CI/CD pipeline failure. Please review the details below and take appropriate action.

  - type: input
    id: commit_hash
    attributes:
      label: Commit Hash
      description: The commit that triggered the failure
      placeholder: e.g., abc123def456
    validations:
      required: true

  - type: input
    id: author
    attributes:
      label: Commit Author
      description: Author of the failing commit
      placeholder: e.g., username or email
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: Branch
      description: Branch where the failure occurred
      placeholder: e.g., main, develop, feature/branch-name
    validations:
      required: true

  - type: dropdown
    id: workflow
    attributes:
      label: Failed Workflow
      description: Which workflow failed?
      options:
        - CI/CD Pipeline
        - Build and Test
        - Code Quality
        - Security Scan
        - Deploy
        - Other
    validations:
      required: true

  - type: dropdown
    id: job
    attributes:
      label: Failed Job
      description: Which job in the workflow failed?
      options:
        - build
        - test
        - code-quality
        - package
        - deploy
        - security-scan
        - Other
    validations:
      required: true

  - type: dropdown
    id: failure_type
    attributes:
      label: Failure Type
      description: What type of failure occurred?
      options:
        - Build Failure
        - Test Failure
        - Code Quality Issues
        - Security Vulnerabilities
        - Deployment Failure
        - Dependency Issues
        - Configuration Error
        - Timeout
        - Other
    validations:
      required: true

  - type: textarea
    id: error_details
    attributes:
      label: Error Details
      description: Detailed error information from the CI/CD logs
      render: text
      placeholder: |
        [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile
        [ERROR] Compilation failure
        [ERROR] /path/to/file.java:[line,column] error message
    validations:
      required: true

  - type: input
    id: workflow_url
    attributes:
      label: Workflow Run URL
      description: Direct link to the failed workflow run
      placeholder: https://github.com/owner/repo/actions/runs/123456789
    validations:
      required: false

  - type: textarea
    id: resolution_steps
    attributes:
      label: Suggested Resolution Steps
      description: Automated suggestions for resolving this failure
      placeholder: |
        Based on the failure type, consider:
        1. Check compilation errors in the code
        2. Verify all dependencies are available
        3. Review recent changes that might have caused the issue
        4. Run tests locally to reproduce the issue
    validations:
      required: false

  - type: checkboxes
    id: investigation_checklist
    attributes:
      label: Investigation Checklist
      description: Steps to investigate and resolve the failure
      options:
        - label: Reviewed the error logs and identified the root cause
        - label: Checked if this is a recurring issue
        - label: Verified the failure is reproducible locally
        - label: Identified the specific change that caused the failure
        - label: Implemented a fix for the issue
        - label: Verified the fix resolves the problem
        - label: Added tests to prevent regression

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any additional context or information about the failure
      placeholder: |
        Related issues: #123
        Previous similar failures: #456
        Environment-specific details...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Next Steps:**
        1. Review the error information and logs above
        2. Fix the underlying issue in your code
        3. Push a new commit to trigger the CI/CD pipeline
        4. This issue will be automatically closed when the pipeline succeeds

        *This issue was automatically generated by the Accordion CI/CD system*
