name: 🔒 安全漏洞 (自动生成)
description: 检测到安全漏洞时自动创建
title: "[Security]: "
labels: ["security", "vulnerability", "high-priority"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **安全警报** ⚠️

        此问题是由于在代码库中检测到安全漏洞而自动创建的。

  - type: dropdown
    id: severity
    attributes:
      label: 严重程度
      description: 安全漏洞的严重程度
      options:
        - 严重
        - 高
        - 中等
        - 低
    validations:
      required: true

  - type: input
    id: vulnerability-id
    attributes:
      label: 漏洞 ID
      description: CVE ID 或其他漏洞标识符
    validations:
      required: false

  - type: input
    id: affected-package
    attributes:
      label: 受影响的包
      description: 受漏洞影响的包或组件
    validations:
      required: true

  - type: input
    id: current-version
    attributes:
      label: 当前版本
      description: 受影响包的当前版本
    validations:
      required: true

  - type: input
    id: fixed-version
    attributes:
      label: 修复版本
      description: 修复漏洞的版本（如果可用）
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: 漏洞描述
      description: 安全漏洞的描述
    validations:
      required: true

  - type: textarea
    id: remediation
    attributes:
      label: 推荐的修复措施
      description: 修复或缓解漏洞的步骤
    validations:
      required: false

  - type: input
    id: scan-date
    attributes:
      label: 扫描日期
      description: 检测到漏洞的时间
    validations:
      required: true