name: 🔒 Security Issue
description: Report security vulnerabilities (use private security advisories for sensitive issues)
title: "[SECURITY] "
labels: ["security", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Important**: For sensitive security vulnerabilities, please use [GitHub Security Advisories](https://github.com/octet-stream/accordion/security/advisories/new) instead of creating a public issue.
        
        This template is for security-related issues that are not sensitive or have already been disclosed.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following
      options:
        - label: This is not a sensitive security vulnerability
          required: true
        - label: I have searched existing security issues
          required: true
        - label: I have read the security policy
          required: true

  - type: dropdown
    id: security_type
    attributes:
      label: Security Issue Type
      description: What type of security issue is this?
      options:
        - Code injection vulnerability
        - Authentication/Authorization issue
        - Input validation problem
        - Dependency vulnerability
        - Configuration security issue
        - Information disclosure
        - Denial of Service (DoS)
        - Security best practice violation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low - Minor security concern
        - Medium - Moderate security risk
        - High - Significant security vulnerability
        - Critical - Severe security vulnerability
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Issue Description
      description: Describe the security issue in detail
      placeholder: |
        The ScriptAction allows execution of arbitrary code without proper sandboxing...
        User input is not properly validated in the EmailAction, allowing...
        The API endpoint exposes sensitive information when...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker achieve by exploiting this issue?
      placeholder: |
        An attacker could:
        - Execute arbitrary code on the server
        - Access sensitive user data
        - Bypass authentication mechanisms
        - Cause denial of service
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the security issue (if safe to share)
      placeholder: |
        1. Create a ScriptAction with malicious payload
        2. Execute the action in a plan
        3. Observe unauthorized access to system resources
        4. Verify the security boundary was bypassed
    validations:
      required: false

  - type: textarea
    id: code_sample
    attributes:
      label: Proof of Concept (if applicable)
      description: Code that demonstrates the security issue (ensure it's safe to share publicly)
      render: java
      placeholder: |
        // Example demonstrating the security issue
        ScriptAction maliciousAction = ScriptAction.builder()
            .script("System.exit(0); // This should not be allowed")
            .build();
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this security issue?
      options:
        - ScriptAction
        - EmailAction
        - ApiAction
        - ShellAction
        - Core framework
        - Session management
        - Authentication
        - Configuration
        - Dependencies
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Environment where the security issue was discovered
      placeholder: |
        OS: Ubuntu 22.04
        Java Version: OpenJDK 17.0.7
        Accordion Version: 1.0.0
        Deployment: Docker container / Standalone JAR / etc.
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How do you suggest fixing this security issue?
      placeholder: |
        - Implement proper input validation for user-provided scripts
        - Add sandboxing for script execution
        - Use allowlists instead of blocklists for dangerous operations
        - Implement proper authentication checks
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to relevant security resources, CVEs, or documentation
      placeholder: |
        - CVE-2023-12345
        - OWASP Top 10: https://owasp.org/www-project-top-ten/
        - Similar vulnerability in other projects: https://...
    validations:
      required: false

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Disclosure preferences
      options:
        - label: I am willing to work with maintainers on responsible disclosure
        - label: I can provide additional details privately if needed
        - label: I would like to be credited for the discovery (if appropriate)

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        Timeline of discovery...
        Related security research...
        Impact on specific use cases...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Security Team Response:**
        - Security issues are prioritized and reviewed promptly
        - We follow responsible disclosure practices
        - Contributors who report security issues may be acknowledged in our security advisories
        
        Thank you for helping keep Accordion secure! 🛡️