package pro.octet.accordion.action.parameters;

import lombok.Builder;
import lombok.Getter;
import lombok.ToString;
import lombok.extern.jackson.Jacksonized;
import pro.octet.accordion.utils.CommonUtils;

/**
 * Script action parameter.
 *
 * @author <a href="https://github.com/eoctet">William</a>
 */
@Getter
@Builder
@ToString
@Jacksonized
public class ScriptParameter {
    /**
     * Script id, Automatically generated by default.
     */
    @Builder.Default
    private String scriptId = CommonUtils.randomString("script");
    /**
     * Script code snippets.
     */
    private String script;
    /**
     * Debug mode, default: false.
     * NOTE: Do not enable it in the production env.
     */
    private boolean debug;
}
