name: CI
on:
  push:
    tags:
      - "v*"

jobs:
  # maven build & deploy
  maven-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'oracle'
          architecture: 'x64'
          cache: 'maven'
          server-id: 'ossrh'
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.MAVEN_PRIVATE_KEY }}

      - name: Build with Maven
        run: |
          mvn clean package deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_REPO_NAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_REPO_CODE }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_PRIVATE_KEY_PASS }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          token: ${{ secrets.DEV_TOKEN }}
