name: Test Security Scan

on:
  workflow_dispatch:
    inputs:
      debug_mode:
        description: 'Enable debug mode'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: read

jobs:
  test-security-scan:
    name: Test OWASP Dependency Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      
      - name: Install jq for JSON parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      
      - name: Debug environment (if enabled)
        if: ${{ inputs.debug_mode == 'true' }}
        run: |
          echo "=== Environment Debug Information ==="
          echo "Maven version:"
          mvn --version
          echo ""
          echo "Java version:"
          java -version
          echo ""
          echo "Project structure:"
          ls -la
          echo ""
          echo "POM.xml content (first 50 lines):"
          head -50 pom.xml
          echo ""
          echo "OWASP suppressions file:"
          cat owasp-suppressions.xml
      
      - name: Run test script
        run: |
          chmod +x scripts/test-security-scan.sh
          ./scripts/test-security-scan.sh
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-security-scan-reports
          path: |
            target/dependency-check-report.*
          retention-days: 7
          if-no-files-found: warn
      
      - name: Display report summary
        if: always()
        run: |
          echo "=== Security Scan Test Summary ==="
          if [ -f "target/dependency-check-report.json" ]; then
            echo "JSON report size: $(du -h target/dependency-check-report.json | cut -f1)"
            if command -v jq &> /dev/null; then
              echo "Vulnerability count: $(jq '.dependencies | map(.vulnerabilities // []) | flatten | length' target/dependency-check-report.json)"
            fi
          fi
          
          if [ -f "target/dependency-check-report.html" ]; then
            echo "HTML report size: $(du -h target/dependency-check-report.html | cut -f1)"
          fi
          
          if [ -f "target/dependency-check-report.xml" ]; then
            echo "XML report size: $(du -h target/dependency-check-report.xml | cut -f1)"
          fi
          
          echo ""
          echo "All files in target directory:"
          ls -la target/ || echo "Target directory not found"